# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ReadBook' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ReadBook
pod 'XSExtension'
pod 'XSUtil'
pod 'SnapKit'
pod 'Kingfisher'
pod 'SQLite.swift'
pod 'Moya/RxSwift'
pod 'NVActivityIndicatorView'
pod 'ObjectMapper'
  # Rx
pod 'RxSwift'
pod 'RxCocoa'
pod 'RxDataSources'
pod 'RxWebKit'

end
